### ISSUE TITLE
Ability to add more shaders repository that the default one

### ISSUE THREAD

**Issue by AnticOwl** [OopyDoopy/ReShade-Centralized#1]
Tested it yesterday and really working well!
Still, only the default shaders are updated not the one added later.

From there my question: would it be possible to add an option where we can put other GitHub repo to check for update?

**Comment by OopyDoopy** [comment]
The current code is pretty naïve, it doesn't check if a file is newer or anything, it just downloads the repos and overwrites every time.   I plan on rewriting that code at some point so that I can make it a bit more intelligent (use the same folder structure as the official installer, only update installed shaders, etc) and when I do I'll probably add the option to add custom repos.  It's not a priority right now though.

Is there a particular repository you'd like added to the installer?

**Comment by CptVeg** [comment]
Not OP but I did raise a similar issue on your work before this (https://github.com/OopyDoopy/ReShade-Tools/issues/3) from what I can see the only repos that you've missed @OopyDoopy are [MLUT](https://github.com/TheGordinho/MLUT), [MadCake](https://github.com/ConstantineRudenko/Shaders/tree/master/reshade/Shaders), [CobraFX](https://github.com/LordKobra/CobraFX/tree/master) and the [RetroArch](https://github.com/Matsilagi/RSRetroArch) package :)

**Comment by OopyDoopy** [comment]
> Not OP but I did raise a similar issue on your work before this ([OopyDoopy/ReShade-Tools#3](https://github.com/OopyDoopy/ReShade-Tools/issues/3)) from what I can see the only repos that you've missed @OopyDoopy are [MLUT](https://github.com/TheGordinho/MLUT), [MadCake](https://github.com/ConstantineRudenko/Shaders/tree/master/reshade/Shaders), [CobraFX](https://github.com/LordKobra/CobraFX/tree/master) and the [RetroArch](https://github.com/Matsilagi/RSRetroArch) package :)
I'll take a look at the pull request to make sure it works and will fix any issues (some repos have some special cases to handle so it's not a guarantee if you didn't test).

**Comment by CptVeg** [comment]
Awesome thanks! I fell in love with the powershell version of this and was so excited to see the next evolution.

**Comment by OopyDoopy** [comment]
Added the missing repos.

> Awesome thanks! I fell in love with the powershell version of this and was so excited to see the next evolution.

No problem, and thank you both for the feedback.

**Comment by AnticOwl** [comment]
Damn, I am late for my reply.
I would like have seen these:
https://github.com/originalnicodr/CorgiFX
https://github.com/luluco250/FXShaders

**Comment by OopyDoopy** [comment]
@AnticOwl Both of those are in there now (in the case of FXShaders, it already was :p).

Also I realized I closed this issue without technically addressing the actual request.  I will probably add support for custom repos eventually, but it will require me to rewrite quite a few things so that it can remain compatible across game installs (rewriting the code for sorting and storing shaders and adding code to track installed repositories and update reshade.ini files with these new paths).  Without that, there's no way to be reasonably sure that a custom repo will work since some files might overwrite others or folder structure might matter.  It's unfortunately a good bit more involved than it seems.
